<?php

require_once('EDANInterface.php');

function search_console_permission() {
  return array(
    'administer search console settings' => array(
      'title' => t('Administer EDAN Search Console Settings'),
      'description' => t('Edit EDAN Search Console Settings.'),
      ),
    'use search console' => array(
      'title' => t('Use EDAN Search Console'),
      'description' => t('Use EDAN Search Console.'),
      ),
    );
}

function search_console_admin() {

  $config = require('config.php');

  $form['search_console_host'] = array(
    '#type' => 'textfield',
    '#title' => t('Host'),
    '#default_value' => variable_get('search_console_host', $config->host),
    );

  $form['search_console_auth_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Authorization Key'),
    '#default_value' => variable_get('search_console_auth_key', $config->auth_key),
    );

  $form['search_console_app_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Application ID'),
    '#default_value' => variable_get('search_console_app_id', $config->app_id),
    );

  return system_settings_form($form);
}

function search_console_menu() {

  $items['search_console'] = array(
    'title' => 'Search Console',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('search_console_form'),
    'access arguments' => array('use search console'),
    );

  $items['full_json'] = array(
    'page callback' => '_full_json_page_callback',
    'page arguments' => array(),
    'access arguments' => array('use search console'),
    );

  $items['full_record'] = array(
    'page callback' => '_full_record_page_callback',
    'page arguments' => array(),
    'access arguments' => array('use search console'),
    );

  $items['search_console_settings'] = array(
    'title' => t('Search Console Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('search_console_admin'),
    'access arguments' => array('administer search console settings'),
    'type' => MENU_CALLBACK,
    );

  return $items;
}

function _full_json_page_callback() {
  $path_parts = arg();
  $query = $path_parts[1];
  $json = _get_search_results_from_edan($query);

  echo '<pre>' . $json . '</pre>';
  exit();
}

function _full_record_page_callback() {
  $path_parts = arg();
  $query = 'q=id:' . $path_parts[1];
  $json = _get_search_results_from_edan($query);

  echo '<pre>' . $json . '</pre>';
  exit();
}

function _get_search_results_from_edan($query = '') {

  $config = require('config.php');
  $host = variable_get('search_console_host', $config->host);
  $authKey = variable_get('search_console_auth_key', $config->auth_key);
  $appId = variable_get('search_console_app_id', $config->app_id);
  // return $resp;
  date_default_timezone_set('UTC');
  // Specify your appid and key below
  $config = array(
    'edan_server' => $host,
    'edan_app_id' => $appId,
    'edan_auth_key' => $authKey,
    'edan_tier_type' => 1,
    );
  // Example usage
  $edan = new EDANInterface($config['edan_server'], $config['edan_app_id'], $config['edan_auth_key'], $config['edan_tier_type']);
  // Request
  $service = 'metadata/v1.1/metadata/search.htm'; // API Endpoint
  // Response
  $results_raw = $edan->sendRequest($query, $service, FALSE, $info = '');
  return $results_raw;
}

function _get_facets_from_edan() {

  $config = require('config.php');
  $host = variable_get('search_console_host', $config->host);
  $authKey = variable_get('search_console_auth_key', $config->auth_key);
  $appId = variable_get('search_console_app_id', $config->app_id);
  // return $resp;
  date_default_timezone_set('UTC');
  // Specify your appid and key below
  $config = array(
    'edan_server' => $host,
    'edan_app_id' => $appId,
    'edan_auth_key' => $authKey,
    'edan_tier_type' => 1,
    );
  // Example usage
  $edan = new EDANInterface($config['edan_server'], $config['edan_app_id'], $config['edan_auth_key'], $config['edan_tier_type']);
  // Request
  $service = 'metadata/v1.1/metadata/getFacets.htm'; // API Endpoint
  // Response
  $results_raw = $edan->sendRequest('', $service, FALSE, $info = '');
  return $results_raw;
}

function search_console_form($form, &$form_state){

  //hide parts of description box
  $js = 'jQuery().ready(function(){
    jQuery(".filter-wrapper").hide();
  });';
  drupal_add_js($js, 'inline');

  if(user_access('administer search console settings')){
    // hyperlink to the admin page for changing authentication settings
    $form['link_to_settings'] = array(
      '#type' => 'item',
      '#markup' => 'Settings may be changed through the ' . l('settings page', '/search_console_settings') . '.',
      );
  }

  $form['group_tabs'] = array(
    '#type'     => 'horizontal_tabs',
    '#attached' => array('library' => array(array('field_group', 'horizontal-tabs'))),
    );

  // Search Field Filters Tab
  $form['search_field_filters_tab'] = array(
    '#type'  => 'fieldset',
    '#title' => t('Filters'),
    '#group' => 'group_tabs',
    );

  $form['search_field_filters_tab']['q'] = array(
    '#title' => t('q'),
    '#type' => 'textfield',
    '#description' => 'The q parameter is normally the main query for the request. See Solr query syntax for more information on different types of queries and syntaxes.',
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['rows'] = array(
    '#title' => t('rows ( 100 max )'),
    '#type' => 'textfield',
    '#default_value' => 10,
    '#description' => 'This parameter is used to paginate results from a query. It specify the maximum number of documents from the complete result set to return to the client for every request. You can consider it as the maximum number of result appear in the page. (default_value value:10)',
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['start'] = array(
    '#title' => t('start ( Do not exceed the maximum number of records! )'),
    '#type' => 'textfield',
    '#default_value' => 1,
    '#description' => 'This parameter is used to paginate results from a query. When specified, it indicates the offset (by default, 1) in the complete result set for the queries where the set of returned documents should begin.',
    '#group' => 'search_field_filters_tab',
    );

  $form['search_field_filters_tab']['record_type'] = array(
    '#type' => 'select',
    '#title' => t('Record Type'),
    '#description' => 'This selection will limit the results to only show records of the selected type.',
    '#options' => array(
      '' => t('Any'),
      'edanmdm' => t('edanmdm'),
      'objectgroup' => t('ogmt'),
      ),
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['facets'] = array(
    '#type' => 'fieldset',
    '#title' => 'Facets',
    '#states' => array(
      'visible' => array(
        ':input[name="record_type"]' => array('value' => 'edanmdm'),
        ),
      ),
    '#group' => 'search_field_filters_tab',
    );

  $form['search_field_filters_tab']['facets']['edanmdm_online_media_type'] = array(
    '#title' => t('online_media_type'),
    '#type' => 'textfield',
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['facets']['edanmdm_object_type'] = array(
    '#title' => t('object_type'),
    '#type' => 'textfield',
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['facets']['edanmdm_topic'] = array(
    '#title' => t('topic'),
    '#type' => 'textfield',
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['facets']['edanmdm_name'] = array(
    '#title' => t('name'),
    '#type' => 'textfield',
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['facets']['edanmdm_culture'] = array(
    '#title' => t('culture'),
    '#type' => 'textfield',
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['facets']['edanmdm_language'] = array(
    '#title' => t('language'),
    '#type' => 'textfield',
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['facets']['edanmdm_place'] = array(
    '#title' => t('place'),
    '#type' => 'textfield',
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['facets']['edanmdm_date'] = array(
    '#title' => t('date'),
    '#type' => 'textfield',
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['facets']['edanmdm_data_source'] = array(
    '#title' => t('data_source'),
    '#type' => 'textfield',
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['facets']['edanmdm_tax_kingdom'] = array(
    '#title' => t('tax_kingdom'),
    '#type' => 'textfield',
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['facets']['edanmdm_tax_phylum'] = array(
    '#title' => t('tax_phylum'),
    '#type' => 'textfield',
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['facets']['edanmdm_tax_class'] = array(
    '#title' => t('tax_class'),
    '#type' => 'textfield',
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['facets']['edanmdm_tax_order'] = array(
    '#title' => t('tax_order'),
    '#type' => 'textfield',
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['facets']['edanmdm_tax_family'] = array(
    '#title' => t('tax_family'),
    '#type' => 'textfield',
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['facets']['edanmdm_scientific_name'] = array(
    '#title' => t('scientific name'),
    '#type' => 'textfield',
    '#group' => 'search_field_filters_tab',
    );
  // submit button
  $form['search_field_filters_tab']['button_container'] = array(
    '#type' => 'item',
    '#attributes' => array('class' => array('container-inline')),
    );
  $form['search_field_filters_tab']['button_container']['submit'] = array(
    '#value' => 'Submit',
    '#type' => 'submit',
    '#name' => 'search_field_filters_submit',
    '#prefix' => '<br>',
    '#group' => 'search_field_filters_tab',
    );
  $form['search_field_filters_tab']['button_container']['clear'] = array(
    '#value' => 'Clear',
    '#type' => 'submit',
    '#name' => 'filters_clear',
    '#group' => 'search_field_filters_tab',
    '#attributes' => array('style' => 'background: #008cba; color: #fff;'),
    );

  // handling for autocomplete tooltip on facet input fields
  drupal_add_library('system', 'ui.autocomplete');
  // following this, autocomplete_options contains an array of facet names that each contains an array of possible facet values for that field
  $autocomplete_options = array();
  $results = json_decode(_get_facets_from_edan(), TRUE);
  foreach ($results['facets'] as $facet_name => $facet_values) {
    foreach ($facet_values as $facet_value) {
      $autocomplete_options[ $facet_name ][] = $facet_value[0];
    }
  }

  $list_of_facet_fields = array(
    'online_media_type',
    'object_type',
    'topic',
    'name',
    'culture',
    'language',
    'place',
    'date',
    'data_source',
    'tax_kingdom',
    'tax_phylum',
    'tax_class',
    'tax_order',
    'tax_family',
    'scientific name',
    );

  // add tooltip script for each field that has existing facets
  foreach ($list_of_facet_fields as $facet_field_name) {
    if (array_key_exists($facet_field_name, $autocomplete_options)) {
      $autocomplete_js = '
      jQuery(document).ready(function() {
        var tags =' . json_encode($autocomplete_options[$facet_field_name]) . ';
        jQuery("#edit-edanmdm-' . str_replace('_', '-', $facet_field_name) . '").autocomplete({
          source: tags,
          minLength: 0
        });
        jQuery("#edit-edanmdm-' . str_replace('_', '-', $facet_field_name) . '").click(function() {
          jQuery("#edit-edanmdm-' . str_replace('_', '-', $facet_field_name) . '").autocomplete( "search", "" );
       });
     });';
     drupal_add_js($autocomplete_js, 'inline');
   }
 }


 $form['query_tab'] = array(
  '#type'  => 'fieldset',
  '#title' => t('Query'),
  '#group' => 'group_tabs',
  );
 $form['query_tab']['query'] = array(
  '#title' => t('Raw Decoded Query'),
  '#type' => 'text_format',
  '#description' => 'You may enter your search filters as a raw query into this field in order to narrow down your search results.',
  '#group' => 'query_tab',
  );
 $form['query_tab']['encoded_query'] = array(
  '#title' => t('Encoded Query'),
  '#type' => 'item',
  '#markup' => '<pre>' . (isset($form_state['encoded_query']) ? $form_state['encoded_query'] : '') . '</pre>',
  '#description' => 'This is a URL-safe encoded query to use in your application.',
  '#group' => 'query_tab',
  );
  // submit button
 $form['query_tab']['button_container'] = array(
  '#type' => 'item',
  '#attributes' => array('class' => array('container-inline')),
  );
 $form['query_tab']['button_container']['submit'] = array(
  '#value' => 'Submit',
  '#type' => 'submit',
  '#name' => 'query_submit',
  '#group' => 'query_tab',
  );
 $form['query_tab']['button_container']['clear'] = array(
  '#value' => 'Clear',
  '#type' => 'submit',
  '#name' => 'query_clear',
  '#group' => 'query_tab',
  '#attributes' => array('style' => 'background: #008cba; color: #fff;'),
  );





 $form['collections_url_tab'] = array(
  '#type'  => 'fieldset',
  '#title' => t('URL'),
  '#group' => 'group_tabs',
  );
 $form['collections_url_tab']['collections_url'] = array(
  '#title' => t('Collections URL'),
  '#type' => 'textfield',
  '#description' => 'Paste a <b><a href="http://collections.si.edu" target="_blank">collection.si.edu</a></b> URL into the field above to replicate the search on this page. You may modify the search using the Search Filters above or by adding requirements to the Raw Query below.',
  '#group' => 'collections_url_tab',
  '#maxlength' => 100000,
  );
 $form['collections_url_tab']['collections_rows'] = array(
  '#title' => t('rows ( 100 max )'),
  '#type' => 'textfield',
  '#default_value' => 10,
  '#description' => 'All Collections.si.edu searches default to <b>10 rows</b>.',
  '#group' => 'collections_url_tab',
  );
  // submit button
 $form['collections_url_tab']['button_container'] = array(
  '#type' => 'item',
  '#attributes' => array('class' => array('container-inline')),
  );
 $form['collections_url_tab']['button_container']['submit'] = array(
  '#value' => 'Submit',
  '#type' => 'submit',
  '#name' => 'collections_url_submit',
  '#prefix' => '<br>',
  '#group' => 'collections_url_tab',
  );
 $form['collections_url_tab']['button_container']['clear'] = array(
  '#value' => 'Clear',
  '#type' => 'submit',
  '#name' => 'collections_clear',
  '#group' => 'collections_url_tab',
  '#attributes' => array('style' => 'background: #008cba; color: #fff;'),
  );

  // this js script handles styling and actions for the clear buttons on all 3 forms
 $clear_button_js = '
 function clear_form_elements(ele) {
  jQuery(ele).find(":input").each(function() {
    switch(this.type) {
      case "password":
      case "select-multiple":
      case "select-one":
      case "text":
      case "textarea":
      if (jQuery(this).attr("id") == "edit-rows") {
        jQuery(this).val("10");
      } else if (jQuery(this).attr("id") == "edit-start") {
        jQuery(this).val("1");
      } else {
        jQuery(this).val("");
      }
      break;
      case "checkbox":
      case "radio":
      this.checked = false;
    }
  });
}
jQuery(document).ready(function() {

  jQuery("#edit-clear, #edit-clear--2, #edit-clear--3").hover(
  function() {
    jQuery(this).css("background", "#0079a1")
  },
  function() {
    jQuery(this).css("background", "#008cba")
  }
  );

  jQuery("#edit-clear, #edit-clear--2, #edit-clear--3").click( function (e) {
    e.preventDefault();
    clear_form_elements(jQuery("#search-console-form"));
  });
});
';
drupal_add_js($clear_button_js, 'inline');

$form['rows_reference'] = array(
 '#type' => 'item',
 '#markup' => isset($form_state['rows_reference']) ? '<b>Number of Records Found:</b><pre>' . $form_state['rows_reference'] . '</pre>' : '',
 );
$form['rows_returned_reference'] = array(
 '#type' => 'item',
 '#markup' => isset($form_state['rows_returned_reference']) ? '<b>Number of Records Returned:</b><pre>' . $form_state['rows_returned_reference'] . '</pre>' : '',
 );
$form['query_reference'] = array(
  '#type' => 'item',
  '#markup' => isset($form_state['query_reference']) ? '<b>Last Valid Query:</b><pre>' . str_replace(' ', '+', urldecode($form_state['query_reference'])) . '</pre>' : '',
  );

  // results display area
$form['group_search_results_tabs'] = array(
  '#type'     => 'horizontal_tabs',
  '#attached' => array('library' => array(array('field_group', 'horizontal-tabs'))),
  );

if(isset($form_state['structured_search_results'])){
  $form['structured_search_results_tab'] = array(
    '#type'  => 'fieldset',
    '#title' => t('Structured Results'),
    '#group' => 'group_search_results_tabs',
    );

  if(!empty($form_state['structured_search_results'])){
    foreach ($form_state['structured_search_results'] as $key => $record) {
      // get fields printed out nicely for the structured search resutls
      $fields = '';
      foreach ($record as $field_key => $field_value) {
        if($field_key != 'content') $fields .= '<strong>' . $field_key . ':</strong> ' . $field_value . "\n";
      }
      // add an image to the result if one exists
      $image = '';
      if (isset($record['content']['descriptiveNonRepeating']['online_media']['mediaCount']) && $record['content']['descriptiveNonRepeating']['online_media']['mediaCount'] >= 1) {
        $image = '<a href="' . $record['content']['descriptiveNonRepeating']['online_media']['media'][0]['content'] . '" target="_blank"><img src="' . $record['content']['descriptiveNonRepeating']['online_media']['media'][0]['thumbnail'] . '" style="max-width: 25%;display: block;margin: auto;"></a>';
      }

      $form['structured_search_results_tab']['structured_search_results'][$key] = array(
        '#type' => 'item',
        '#markup' => '<pre>' .
        ( !empty($image) ?
        '<div style="float:left; max-width: 70%; padding-right: 5%;">' . $fields . '</div>' . $image
        :
        '<div style="float:left; max-width: 100%;">' . $fields . '</div>' ) .
        '<a href="/full_record/' . $record['id'] . '" target="_blank" style="float: left;clear: both;">View Full Record</a>
        </pre>',
        '#group' => 'structured_search_results_tab',
        );
    }
  }else{
    drupal_set_message('Your search returned no results. This may be due to a lack of matching records within EDAN or an invalid parameter. Please check that all of your parameters are set correctly.', 'warning');
    $form['structured_search_results_tab']['structured_search_results'] = array(
      '#type' => 'item',
      '#markup' => '<pre>The Query returned no results.</pre>',
      '#group' => 'structured_search_results_tab',
      );
  }
}

if(isset($form_state['raw_json_results'])){

  $form['raw_json_results_tab'] = array(
    '#type'  => 'fieldset',
    '#title' => t('Raw JSON Results'),
    '#group' => 'group_search_results_tabs',
    );


  if(!empty($form_state['raw_json_results'])) {
    if(substr_count( $form_state['raw_json_results'], "\n" ) <= 1000){
      $output = $form_state['raw_json_results'];
      $link_to_fulltext = '';
    }else {
      $lines = explode("\n", $form_state['raw_json_results']);
      $output = implode("\n", array_slice($lines, 0, 1000));
      $link_to_fulltext = '<a href="/full_json/' . $form_state['query_reference'] . '"" target="_blank">Click to view full JSON</a>';
    }

    $copy_js = 'jQuery().ready(function(){

      jQuery("#edit-copy-to-clipboard").click( function (e) {
        e.preventDefault();
        var temp = jQuery("<input>");
        jQuery("body").append(temp);
        temp.val(jQuery("#holdtext").text()).select();
        document.execCommand("copy");
        temp.remove();
      });

    });';
    drupal_add_js($copy_js, 'inline');

    $form['raw_json_results_tab']['copy_to_clipboard'] = array(
      '#value' => 'Copy to Clipboard',
      '#type' => 'submit',
      '#name' => 'copy',
      '#group' => 'raw_json_results_tab',
      '#attributes' => array('style' => '-webkit-border-radius: 0px;'),
      );

      // print out the json output
    $form['raw_json_results_tab']['raw_json_results'] = array(
      '#type' => 'item',
      '#markup' =>
      '<div id="holdtext" style="display:none;">' . $form_state['raw_json_results'] . '</div>
      <pre>' . $output . '</pre>' . $link_to_fulltext,
      '#group' => 'raw_json_results_tab',
      );
  }
}
if(!empty($form_state['structured_search_results']) || !empty($form_state['raw_json_results'])){
  $form['link_to_top'] = array(
    '#type' => 'item',
    '#markup' => '<a href="#">Back to top of page</a>',
    );
}

return $form;
}

function search_console_form_submit($form, &$form_state) {

  // initialize the empty query that will eventually be submitted to EDAN for results
  $query = '';

  // check which tab on the search form submitted to this function and therefore, which fields need to be checked for relevant data
  switch($form_state['triggering_element']['#name']){

    // this is the filters tab form
    case 'search_field_filters_submit':

    // add optional parameters if they are set
    $query_parameters = array();
    $query_parameters['q'] = !empty($form_state['values']['q']) ? $form_state['values']['q'] : '';
    $query_parameters['rows'] = !empty($form_state['values']['rows']) ? $form_state['values']['rows'] : '0';
    $query_parameters['start'] = !empty($form_state['values']['start']) ? $form_state['values']['start'] : '1';
    $query_parameters['fqs'] = array();

    // build out the fqs from applicable, set facets and set record type according to dropdown selection
    if(isset($form_state['values']['record_type']) && !empty($form_state['values']['record_type'])){
      // look for only records of type record_type
      $record_type = $form_state['values']['record_type'];
      $query_parameters['fqs'][] = 'type:' . $record_type;

      // add facets to search
      foreach ($form_state['values'] as $key => $value) {
        // if this field is of the type that starts with the current record type, then add it to the parameters array
        if(substr($key, 0, strlen($record_type)) == $record_type && !empty($value)){
          $query_parameters['fqs'][] = str_replace($record_type . '_', '', $key) . ':' . $value;
        }
      }
    }

    // build out the final query
    $query = 'fqs=[';
    // add all fq parameters as fqs to the final query first
    $last_element_in_array = count($query_parameters['fqs']) - 1;
    foreach ($query_parameters['fqs'] as $key => $fq) {
      $query .= '"' . str_replace(',', '+', $fq) . '"';
      // add comma if this is not the last element
      if ($key != $last_element_in_array) {
        $query .= ',';
      }
    }
    $query .= ']';
    // unset fqs from the parameters to make sure it's not reapplied
    unset($query_parameters['fqs']);
    foreach ($query_parameters as $key => $value) {
      // only add the ampersand if the query is not empty
      if (!empty($query)) {
        $query .= '&';
      }
      // add value to the query
      $query .= $key . '=' . str_replace(',', '+', $value);
    }

    // get rid of unnecessary spaces in the query
    $query = str_replace(' ', '+', $query);
    $query = preg_replace('/[++]+/', '+', $query);

    // set form reference for the final query
    $form_state['query_reference'] = $query;

    // set query on the query tab
    $form_state['input']['query']['value'] = $query;
    $form_state['encoded_query'] = urlencode($query);
    $form_state['input']['collections_rows'] = $query_parameters['rows'];
    break;


    // this is the collections url form
    case 'collections_url_submit':
      // get the query from a collections.si.edu url
    if(!empty($form_state['values']['collections_url'])){

      // reset the filters fields
      $form_state['input']['q'] = '';
      $form_state['input']['rows'] = 10;
      $form_state['input']['start'] = 1;

      // set query
      $temp_query = end(explode('http://collections.si.edu/search/results.htm?', urldecode($form_state['values']['collections_url'])));
      $temp_query_parameters = explode('&', $temp_query);
      $query_parameters = array();
      $query_parameters['fqs'] = array();
      // set the key to the parameter name and the value to just the value
      foreach ($temp_query_parameters as $temp_query_param) {
        // the key in this case is the parameter
        $key = reset(explode('=', $temp_query_param));
        // the value is what the parameter is set to
        $value = end(explode('=', $temp_query_param));
        switch ($key) {
          case 'fq':
          $sanitized_value = str_replace('"', '', urldecode($value));
          $query_parameters['fqs'][] = $sanitized_value;
          break;
          case 'q':
          $query_parameters['q'] = $value;
            // set the filters on the filters tab
          $form_state['input']['q'] .= $value;
          break;
          default:
          $query_parameters[$key] = $value;
            // set the filters on the filters tab
          if (isset($form_state['input'][$key])) {
            $form_state['input'][$key] = $value;
          }
          break;
        }
      }

      // build out the final query
      $query = 'fqs=[';
      // add all fq parameters as fqs to the final query first
      $last_element_in_array = count($query_parameters['fqs']) - 1;
      foreach ($query_parameters['fqs'] as $key => $fq) {
        $query .= str_replace(',', '+', $fq);
        // add comma if this is not the last element
        if ($key != $last_element_in_array) {
          $query .= ',';
        }

        // set the filters on the filters tab
        $fq_key = reset(explode(':', $fq));
        $fq_value = end(explode(':', $fq));
        if (isset($form_state['input']['edanmdm_' . $fq_key ])) {
          $form_state['input']['edanmdm_' . $fq_key ] = $fq_value;
        }
      }
      $query .= ']';
      // unset fqs from the parameters to make sure it's not reapplied
      unset($query_parameters['fqs']);
      foreach ($query_parameters as $key => $value) {
        // only add the ampersand if the query is not empty
        if (!empty($query)) {
          $query .= '&';
        }
        // add value to the query
        $query .= $key . '=' . str_replace(',', '+', $value);
      }
      // add rows to the final query if necessary
      if (!empty($form_state['input']['collections_rows'])) {
        $query .= '&rows=' . $form_state['input']['collections_rows'];
        $form_state['input']['rows'] = $form_state['input']['collections_rows'];
      }

      // get rid of unnecessary spaces in the query
      $query = str_replace(' ', '+', $query);
      $query = preg_replace('/[+]{2,}/', '+', $query);

      // set form reference for the final query
      $form_state['query_reference'] = $query;

      // set query on the query tab
      $form_state['input']['query']['value'] = $query;
      $form_state['encoded_query'] = urlencode($query);
      $form_state['input']['record_type'] = 'edanmdm';
    }
    break;


    // this is the simple query form
    case 'query_submit':
    if(!empty($form_state['values']['query']['value'])){
      $query = str_replace(' ', '+', $form_state['values']['query']['value']);
        // set the encoded query for reference
      $form_state['encoded_query'] = urlencode($query);
    }
    $form_state['query_reference'] = $query;


    // reset the filters fields
    $form_state['input']['q'] = '';
    $form_state['input']['rows'] = 10;
    $form_state['input']['start'] = 1;
    $form_state['input']['collections_url'] = '';
    // fill in the other tabs using the query as reference
    $temp_query_parameters = explode('&', $query);
    $query_parameters['fqs'] = array();
    foreach ($temp_query_parameters as $temp_query_param) {
      // the key in this case is the parameter
      $key = reset(explode('=', $temp_query_param));
      // the value is what the parameter is set to
      $value = end(explode('=', $temp_query_param));
      switch ($key) {
        case 'fqs':
        $fqs_array = explode(',', str_replace('"', '', substr($value, 1, -1)));
        foreach ($fqs_array as $fq) {
          $query_parameters['fqs'][] = $fq;
        }
        break;
        case 'q':
        $form_state['input']['q'] .= $value;
        break;
        case 'rows':
        $form_state['input']['rows'] = $value;
        $form_state['input']['collections_rows'] = $value;
        break;
        default:
        if (isset($form_state['input'][$key])) {
          $form_state['input'][$key] = $value;
        }
        break;
      }
    }
    foreach ($query_parameters['fqs'] as $key => $fq) {
      // set the filters on the filters tab
      $fq_key = reset(explode(':', $fq));
      $fq_value = end(explode(':', $fq));
      if (isset($form_state['input']['edanmdm_' . $fq_key ])) {
        $form_state['input']['edanmdm_' . $fq_key ] = $fq_value;
      }
    }
    break;
  }

  // this block submits the query to EDAN and cleans up/prints out the results for the user
  if(!empty($query)){

    // error handling section
    $query_parameters = array();
    $parameter_array = explode('&', $query);
    foreach ($parameter_array as $value) {
     list($k, $v) = explode('=', $value);
     $query_parameters[$k] = $v;
   }
    // q is empty
   if (!isset($query_parameters['q']) || empty($query_parameters['q'])) {
    drupal_set_message('You have not entered a "q" value! Your EDAN search will return a list of generic records.', 'warning');
  }
    // rows is invalid
  if (!isset($query_parameters['rows']) || !is_numeric($query_parameters['rows']) || $query_parameters['rows'] <= 0) {
    drupal_set_message('The "rows" value you have entered seems to be invalid (' . (isset($query_parameters['rows']) ? $query_parameters['rows'] : 'EMPTY VALUE') . '). Make sure that "rows" is a positive integer between 1 and 100.', 'warning');
  }
    // start is invalid
  if (!isset($query_parameters['start']) || !is_numeric($query_parameters['start']) || $query_parameters['start'] < 0) {
    drupal_set_message('The "start" value you have entered seems to be invalid (' . (isset($query_parameters['start']) ? $query_parameters['start'] : 'EMPTY VALUE') . '). Make sure that "start" is a positive integer above 0.', 'warning');
  }

    // set the raw json results
  $raw_json_results = _get_search_results_from_edan(isset($query) ? $query : '');
  $form_state['raw_json_results'] = $raw_json_results;

    // set the structured search results
  $raw_json = json_decode($raw_json_results, true);
  if(isset($raw_json['rows'])){
    $form_state['rows_reference'] = $raw_json['numFound'];
    $form_state['rows_returned_reference'] = count($raw_json['rows']);
      // reset the results
    $form_state['structured_search_results'] = array();
      // add rows to results
    foreach ($raw_json['rows'] as $key => $record) {
      $form_state['structured_search_results'][] = $record;
    }
  }else{
    drupal_set_message('Something went wrong. Please contact an Administrator.', 'error');
  }
}else{
  drupal_set_message('The search parameters are invalid. Please adjust your search and try again or contact an Administrator.', 'error');
}

  // rebuild the form with new inputs and results set
$form_state['rebuild'] = TRUE;
}
