<?php

require_once('EDANInterface.php');
include('utilities.inc');

function search_console_permission() {
  return array(
    'administer search console settings' => array(
      'title' => t('Administer EDAN Search Console Settings'),
      'description' => t('Edit EDAN Search Console Settings.'),
      ),
    'use search console' => array(
      'title' => t('Use EDAN Search Console'),
      'description' => t('Use EDAN Search Console.'),
      ),
    );
}

function search_console_menu() {

  $items['search_console'] = array(
    'title' => 'Search Console',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('search_console_form'),
    'access arguments' => array('use search console'),
    'file' => 'search_console.main.inc',
    'file path' => drupal_get_path('module', 'search_console'),
    );

  $items['full_json'] = array(
    'page callback' => '_full_json_page_callback',
    'page arguments' => array(),
    'access arguments' => array('use search console'),
    'type' => MENU_CALLBACK,
    'file' => 'search_console.json.inc',
    'file path' => drupal_get_path('module', 'search_console'),
    );

  $items['full_record'] = array(
    'page callback' => '_full_record_page_callback',
    'page arguments' => array(),
    'access arguments' => array('use search console'),
    'type' => MENU_CALLBACK,
    'file' => 'search_console.record.inc',
    'file path' => drupal_get_path('module', 'search_console'),
    );

  $items['facets_reference_guide'] = array(
    'page callback' => '_facets_guide_page_callback',
    'access arguments' => array('use search console'),
    'type' => MENU_CALLBACK,
    'file' => 'search_console.facets.inc',
    'file path' => drupal_get_path('module', 'search_console'),
    );

  $items['search_console_settings'] = array(
    'title' => t('Search Console Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('search_console_admin'),
    'access arguments' => array('administer search console settings'),
    'type' => MENU_CALLBACK,
    'file' => 'search_console.admin.inc',
    'file path' => drupal_get_path('module', 'search_console'),
    );

  return $items;
}
